### ISSUE TITLE
The deployment is failing because deployment URL is wrong

### ISSUE THREAD

**Issue by jackfiallos** [amondnet/vercel-action#173] opened 2022-07-13 08:52 UTC
Hello guys,

A few days ago started seeing this error happening when deploying:

```bash
...
set preview-url output
set preview-url output as first alias
using scope
/usr/local/bin/npx vercel inspect Vercel CLI 27.0.1  (beta) — https://vercel.com/feedback
https://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app/ -t *** --scope ***
Vercel CLI 27.0.1
Vercel CLI 27.0.1
Fetching deployment "Vercel CLI 27.0.1  (beta) — [https://vercel.com/feedback\nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app](https://vercel.com/feedback/nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app)" in jackfiallos
Fetching deployment "Vercel CLI 27.0.1  (beta) — [https://vercel.com/feedback\nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app](https://vercel.com/feedback/nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app)" in jackfiallos
Error! Failed to find deployment "Vercel CLI 27.0.1  (beta) — [https://vercel.com/feedback\nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app](https://vercel.com/feedback/nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app)" in jackfiallos
Error! Failed to find deployment "Vercel CLI 27.0.1  (beta) — [https://vercel.com/feedback\nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app](https://vercel.com/feedback/nhttps://tracking-portal-d1zq6lrp1-jackfiallos.vercel.app)" in jackfiallos
Error: The process '/usr/local/bin/npx' failed with exit code 1
...
```

But I haven't changed anything, so I decided to follow what this action is doing under the hood and everything works fine, so the only thing I notice is wrong is the deployment URL because is appending `https://vercel.com/feedback\n` to the output URL when fetching the deployment.

Any ideas why this is happening or how to solve it.

Thanks

**Comment by dnlml** [comment] 2022-07-13 13:46
Same problem here, the deploy is successful but the pipeline output an error

**Comment by danmilgram** [comment] 2022-07-13 16:57
Same here guys

**Comment by yolken-airplane** [comment] 2022-07-13 18:14
For those using a local fork- you can fix by changing `vercel` to `vercel@25.0.1` in all of the `npx` invocations in `index.js`, then re-run `npm run package`.

**Comment by jackfiallos** [comment] 2022-07-13 19:02
there's potentially a PR that could fix this https://github.com/amondnet/vercel-action/pull/171 and sorry, that I didn't read the previous issue which is somehow related this one

**Comment by vitorbal** [comment] 2022-07-13 21:28
This looks like a duplicate of https://github.com/amondnet/vercel-action/issues/170

**Closed** 2022-07-14 09:41 UTC
